export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import GameProvider from '../context/GameContext';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GameProvider>
          {children}
        </GameProvider>
      </body>
    </html>
  )
}
